version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: api-springblog-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springboot_blog 
    ports:
      - "3306:3306"
    networks:
      - springblog-network
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-springblog
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springboot_blog
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - springblog-network

volumes:
  mysql_data:

networks:
  springblog-network:
    driver: bridge
    
